import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { geistSans } from './fonts'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={geistSans.className}>
      <head>
        <script async src="https://tally.so/widgets/embed.js"></script>
      </head>
      <body>{children}</body>
    </html>
  )
}
