import { Inter } from 'next/font/google'
import "./globals.css"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
      <head>
        <script async src="https://tally.so/widgets/embed.js"></script>
      </head>
      <body>{children}</body>
    </html>
  )
}
